version: '3'
services:
  hass:
    container_name: hass
    image: homeassistant/home-assistant:0.74.2
    ports:
      - "8123:8123"
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
  appdaemon:
    container_name: appdaemon
    build:
      context: .
      dockerfile: Dockerfile.appdaemon
    volumes:
      - ./appdaemon-config:/conf
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - hass
    environment:
      - HA_URL=http://hass:8123
    restart: always
