version: '3'
services:
  hass:
    container_name: hass
    image: homeassistant/home-assistant:0.74.2
    ports:
      - "8123:8123"
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:3.0.1
    volumes:
      - ../appdaemon:/conf:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - hass
    environment:
      - HA_URL=http://127.0.0.1:8123
    restart: always
    network_mode: host
