homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.753790
  longitude: -84.245627
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 299
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

zone:
  - name: Work
    longitude: -84.3514511
    latitude: 33.9282418
    radius: 300
    icon: mdi:office-building
  # I want 50m radius for "Home", not the default 100m
  - name: Home
    latitude: 33.753790
    longitude: -84.245627
    radius: 50
    icon: mdi:house

# Enables the frontend
frontend:

# Enables configuration UI
config:

recorder:

statsd:
  host: 192.168.0.24
  log_attributes: true
  value_mapping:
    on: 1
    open: 1
    off: 0
    closed: 0
    cooling: 1
    heating: 2
    idle: 0
    home: 1
    away: 0
    Disarmed: 0
    Home: 1
    Away: 2

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - group.all_automations
      - group.all_devices
      - group.all_lights
      - group.all_switches
      - group.doors
      - group.motion
      - sensor.bedroomsensor_alarm_level
      - sensor.bedroomsensor_alarm_type
      - sensor.bedroomsensor_appliance
      - sensor.bedroomsensor_burglar
      - sensor.bedroomsensor_clock
      - sensor.bedroomsensor_emergency
      - sensor.bedroomsensor_homehealth
      - sensor.bedroomsensor_power_management
      - sensor.bedroomsensor_sourcenodeid
      - sensor.bedroomsensor_system
      - sensor.cam1_events
      - sensor.cam2_events
      - sensor.cam3_events
      - sensor.cam4_events
      - sensor.ecolink_doorwindow_sensor_access_control
      - sensor.ecolink_doorwindow_sensor_access_control_2
      - sensor.ecolink_doorwindow_sensor_access_control_3
      - sensor.ecolink_doorwindow_sensor_access_control_4
      - sensor.ecolink_doorwindow_sensor_alarm_level
      - sensor.ecolink_doorwindow_sensor_alarm_level_2
      - sensor.ecolink_doorwindow_sensor_alarm_level_3
      - sensor.ecolink_doorwindow_sensor_alarm_level_4
      - sensor.ecolink_doorwindow_sensor_alarm_type
      - sensor.ecolink_doorwindow_sensor_alarm_type_2
      - sensor.ecolink_doorwindow_sensor_alarm_type_3
      - sensor.ecolink_doorwindow_sensor_alarm_type_4
      - sensor.ecolink_doorwindow_sensor_burglar
      - sensor.ecolink_doorwindow_sensor_burglar_2
      - sensor.ecolink_doorwindow_sensor_burglar_3
      - sensor.ecolink_doorwindow_sensor_burglar_4
      - sensor.ecolink_doorwindow_sensor_power_management
      - sensor.ecolink_doorwindow_sensor_power_management_2
      - sensor.ecolink_doorwindow_sensor_power_management_3
      - sensor.ecolink_doorwindow_sensor_power_management_4
      - sensor.ecolink_doorwindow_sensor_sourcenodeid
      - sensor.ecolink_doorwindow_sensor_sourcenodeid_2
      - sensor.ecolink_doorwindow_sensor_sourcenodeid_3
      - sensor.ecolink_doorwindow_sensor_sourcenodeid_4
      - sensor.ecolink_motion_detector_alarm_level
      - sensor.ecolink_motion_detector_alarm_type
      - sensor.ecolink_motion_detector_burglar
      - sensor.ecolink_motion_detector_power_management
      - sensor.ecolink_motion_detector_sourcenodeid
      - sensor.kitchensensor_alarm_level
      - sensor.kitchensensor_alarm_type
      - sensor.kitchensensor_appliance
      - sensor.kitchensensor_burglar
      - sensor.kitchensensor_homehealth
      - sensor.kitchensensor_power_management
      - sensor.kitchensensor_sourcenodeid
      - sensor.lrmotion_alarm_level
      - sensor.lrmotion_alarm_type
      - sensor.lrmotion_burglar
      - sensor.lrmotion_clock
      - sensor.lrmotion_emergency
      - sensor.lrmotion_homehealth
      - sensor.lrmotion_power_management
      - sensor.lrmotion_sourcenodeid
      - sensor.officesensor_alarm_level
      - sensor.officesensor_alarm_type
      - sensor.officesensor_burglar
      - sensor.officesensor_clock
      - sensor.officesensor_emergency
      - sensor.officesensor_homehealth
      - sensor.officesensor_power_management
      - sensor.officesensor_sourcenodeid
      - sensor.officesensor_system
      - weather.dark_sky

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Dark Sky

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

switch:
  - platform: zoneminder
    command_on: Modect
    command_off: Monitor

# Text to speech
tts:
  - platform: google

# Cloud
# cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zoneminder:
  host: localhost

camera:
  - platform: zoneminder

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0x9F, 0x72, 0x4E, 0xD6, 0x21, 0x27, 0x4E, 0x4F, 0x11, 0xEC, 0x49, 0xCD, 0x40, 0x52, 0x12, 0x36"
  device_config:
    zwave.2gig_technologies_ct101_thermostat_iris:
      polling_intensity: 1
    climate.2gig_technologies_ct101_thermostat_iris_cooling_1:
      polling_intensity: 1
    climate.2gig_technologies_ct101_thermostat_iris_heating_1:
      polling_intensity: 1
    sensor.2gig_technologies_ct101_thermostat_iris_temperature:
      polling_intensity: 1

device_tracker:
  - platform: gpslogger
    password: !secret gpstracker_password

proximity:
  home:
    ignored_zones:
      - work
    devices:
      - device_tracker.02157df2c2d6e627
    unit_of_measurement: m

notify:
  - name: gmail
    platform: smtp
    sender: jason@jasonantman.com
    recipient: jason@jasonantman.com
    server: smtp.gmail.com
    port: 587
    username: !secret gmail_username
    password: !secret gmail_password
    encryption: starttls
    sender_name: HomeAssistant
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

input_boolean:
  trigger_first_morning:
    name: Waiting for first morning motion
    icon: mdi:kettle
  cameras_silent:
    name: Silence ZoneMinder Alerts
    icon: mdi:volume-off
  no_alarm_delay:
    name: Disable Away Alarm Delay
  arming_away:
    name: Arming Away From Panel
  trigger_delay:
    name: Alarm Triggered But Delaying

input_select:
  alarmstate:
    name: Alarm State
    options:
      - Home
      - Away
      - Disarmed

climate:
  platform: zwave
