# see: https://github.com/ciotlosm/docs-lovelace
name: Non-Shitty UI
views:
  - name: Main
    title: Main
    id: main
    theme: this-doesnt-work
    cards:
      # LEFT COLUMN
      - type: vertical-stack
        cards:
        - type: picture-elements
          image: /local/floorplan.jpg
          elements:
            # BULBS
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level # Kitchen bulb
              style:
                top: 56%
                left: 27%
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level_2 # Kitchen bulb 2
              style:
                top: 47%
                left: 27%
            - type: state-icon
              tap_action: toggle
              entity: light.zipato_bulb_2_level # Porch bulb
              style:
                top: 89%
                left: 7%
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level_3 # Porch bulb 2
              style:
                top: 89%
                left: 2%
            - type: state-icon
              tap_action: toggle
              entity: switch.livingroomlight_switch
              style:
                top: 95%
                left: 25%
            # DOORS
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_2 # crawlspace
              style:
                top: 93%
                left: 86%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_3 # Gate
              style:
                top: 6%
                left: 96%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_4 # kitchen
              style:
                top: 40%
                left: 19%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor # front
              style:
                top: 89%
                left: 14%
            # MOTION
            - type: state-icon
              entity: binary_sensor.ecolink_motion_detector_sensor # back bedroom
              style:
                top: 13%
                left: 65%
            - type: state-icon
              entity: binary_sensor.kitchen_motion # kitchen
              style:
                top: 56%
                left: 18%
            - type: state-icon
              entity: binary_sensor.livingroom_motion # living room
              style:
                top: 80%
                left: 35%
            - type: state-icon
              entity: binary_sensor.office_motion # office
              style:
                top: 82%
                left: 75%
            - type: state-icon
              entity: binary_sensor.bedroom_motion # bedroom
              style:
                top: 50%
                left: 75%
            # CAMERAS
            - type: state-icon
              entity: camera.cam1 # CAM1
              style:
                top: 68%
                left: 16%
            - type: state-icon
              entity: camera.cam2 # CAM2
              style:
                top: 8%
                left: 30%
            - type: state-icon
              entity: camera.cam3 # CAM3
              style:
                top: 73%
                left: 5%
            - type: state-icon
              entity: camera.cam4 # CAM4
              style:
                top: 6%
                left: 88%
            # TEMPERATURES
            - type: state-label
              entity: sensor.bedroomsensor_temperature
              style:
                top: 50%
                left: 66%
            - type: state-label
              entity: sensor.pi2graphite_1wire_bedroom
              style:
                top: 42%
                left: 78%
            - type: state-label
              entity: sensor.pi2graphite_1wire_office
              style:
                top: 94%
                left: 65%
            - type: state-label
              entity: sensor.officesensor_temperature
              style:
                top: 94%
                left: 77%
            - type: state-label
              entity: sensor.kitchensensor_temperature
              style:
                top: 48%
                left: 20%
            - type: state-label
              entity: sensor.lrmotion_temperature
              style:
                top: 90%
                left: 35%
            - type: state-label
              entity: sensor.2gig_technologies_ct101_thermostat_iris_temperature
              style:
                top: 65%
                left: 40%
        - type: picture-entity
          entity: switch.cam3_state
          camera_image: camera.cam3
        - type: entities
          title: Z-Wave
          entities:
            - zwave.aeotec_zw090_zstick_gen5_us
            - zwave.2gig_technologies_ct101_thermostat_iris
            - zwave.bedroomsensor
            - zwave.ecolink_doorwindow_sensor
            - zwave.ecolink_doorwindow_sensor_2
            - zwave.ecolink_doorwindow_sensor_3
            - zwave.ecolink_doorwindow_sensor_4
            - zwave.ecolink_motion_detector
            - zwave.inovelli_unknown_type2400_id2400
            - zwave.kitchensensor
            - zwave.linear_lb60z1_dimmable_led_light_bulb
            - zwave.linear_lb60z1_dimmable_led_light_bulb_2
            - zwave.linear_lb60z1_dimmable_led_light_bulb_3
            - zwave.lrmotion
            - zwave.officesensor
            - zwave.zipato_bulb_2
      # CENTER COLUMN
      - type: vertical-stack
        cards:
        - type: entities
          show_header_toggle: false
          title: Controls
          entities:
            - input_select.alarmstate
            - input_boolean.cameras_silent
            - input_boolean.no_alarm_delay
            - group.lights
        - type: picture-entity
          entity: switch.cam2_state
          camera_image: camera.cam2
        - type: picture-entity
          entity: switch.cam1_state
          camera_image: camera.cam1
      # RIGHT COLUMN
      - type: vertical-stack
        cards:
        - type: entities
          title: Climate
          entities:
            - sensor.thermostat_fan_state
            - sensor.thermostat_operation_mode
            - climate.2gig_technologies_ct101_thermostat_iris_cooling_1
            - climate.2gig_technologies_ct101_thermostat_iris_heating_1
        - type: picture-entity
          entity: switch.cam4_state
          camera_image: camera.cam4
        - type: weather-forecast
          entity: weather.dark_sky
        - type: entities
          show_header_toggle: false
          title: Cameras
          entities:
            - sensor.cam1_events
            - sensor.cam1_status
            - switch.cam1_state
            - sensor.cam2_events
            - sensor.cam2_status
            - switch.cam2_state
            - sensor.cam3_events
            - sensor.cam3_status
            - switch.cam3_state
            - sensor.cam4_events
            - sensor.cam4_status
            - switch.cam4_state
      # END RIGHT COLUMN - NO MORE COLUMNS!
  - name: FireTV
    title: FireTV
    id: firetv
    theme: this-doesnt-work
    cards:
      # LEFT COLUMN
      - type: vertical-stack
        cards:
        - type: picture-elements
          image: /local/floorplan.jpg
          elements:
            # BULBS
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level # Kitchen bulb
              style:
                top: 56%
                left: 27%
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level_2 # Kitchen bulb 2
              style:
                top: 47%
                left: 27%
            - type: state-icon
              tap_action: toggle
              entity: light.zipato_bulb_2_level # Porch bulb
              style:
                top: 89%
                left: 7%
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level_3 # Porch bulb 2
              style:
                top: 89%
                left: 2%
            - type: state-icon
              tap_action: toggle
              entity: switch.livingroomlight_switch
              style:
                top: 95%
                left: 25%
            # DOORS
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_2 # crawlspace
              style:
                top: 93%
                left: 86%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_3 # Gate
              style:
                top: 6%
                left: 96%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_4 # kitchen
              style:
                top: 40%
                left: 19%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor # front
              style:
                top: 89%
                left: 14%
            # MOTION
            - type: state-icon
              entity: binary_sensor.ecolink_motion_detector_sensor # back bedroom
              style:
                top: 13%
                left: 65%
            - type: state-icon
              entity: binary_sensor.kitchen_motion # kitchen
              style:
                top: 56%
                left: 18%
            - type: state-icon
              entity: binary_sensor.livingroom_motion # living room
              style:
                top: 80%
                left: 35%
            - type: state-icon
              entity: binary_sensor.office_motion # office
              style:
                top: 82%
                left: 75%
            - type: state-icon
              entity: binary_sensor.bedroom_motion # bedroom
              style:
                top: 50%
                left: 75%
            # CAMERAS
            - type: state-icon
              entity: camera.cam1 # CAM1
              style:
                top: 68%
                left: 16%
            - type: state-icon
              entity: camera.cam2 # CAM2
              style:
                top: 8%
                left: 30%
            - type: state-icon
              entity: camera.cam3 # CAM3
              style:
                top: 73%
                left: 5%
            - type: state-icon
              entity: camera.cam4 # CAM4
              style:
                top: 6%
                left: 88%
            # TEMPERATURES
            - type: state-label
              entity: sensor.bedroomsensor_temperature
              style:
                top: 50%
                left: 66%
            - type: state-label
              entity: sensor.pi2graphite_1wire_bedroom
              style:
                top: 42%
                left: 78%
            - type: state-label
              entity: sensor.pi2graphite_1wire_office
              style:
                top: 94%
                left: 65%
            - type: state-label
              entity: sensor.officesensor_temperature
              style:
                top: 94%
                left: 77%
            - type: state-label
              entity: sensor.kitchensensor_temperature
              style:
                top: 48%
                left: 20%
            - type: state-label
              entity: sensor.lrmotion_temperature
              style:
                top: 90%
                left: 35%
            - type: state-label
              entity: sensor.2gig_technologies_ct101_thermostat_iris_temperature
              style:
                top: 65%
                left: 40%
        - type: picture-entity
          entity: switch.cam3_state
          camera_image: camera.cam3
      # CENTER COLUMN
      - type: vertical-stack
        cards:
        - type: entities
          show_header_toggle: false
          title: Controls
          entities:
            - input_select.alarmstate
            - input_boolean.cameras_silent
            - input_boolean.no_alarm_delay
            - group.lights
        - type: picture-entity
          entity: switch.cam2_state
          camera_image: camera.cam2
        - type: picture-entity
          entity: switch.cam1_state
          camera_image: camera.cam1
      # RIGHT COLUMN
      - type: vertical-stack
        cards:
        - type: entities
          title: Climate
          entities:
            - sensor.thermostat_fan_state
            - sensor.thermostat_operation_mode
            - climate.2gig_technologies_ct101_thermostat_iris_cooling_1
            - climate.2gig_technologies_ct101_thermostat_iris_heating_1
        - type: picture-entity
          entity: switch.cam4_state
          camera_image: camera.cam4
        - type: weather-forecast
          entity: weather.dark_sky
      # END RIGHT COLUMN - NO MORE COLUMNS!
