# see: https://github.com/ciotlosm/docs-lovelace
name: Non-Shitty UI
views:
  - name: Main
    title: Main
    id: main
    theme: this-doesnt-work
    cards:
      # LEFT COLUMN
      - type: vertical-stack
        cards:
        - type: picture-elements
          image: /local/floorplan.jpg
          elements:
            # BULBS
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level # Kitchen bulb
              style:
                top: 56%
                left: 27%
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level_2 # Kitchen bulb 2
              style:
                top: 47%
                left: 27%
            - type: state-icon
              tap_action: toggle
              entity: light.zipato_bulb_2_level # Porch bulb
              style:
                top: 89%
                left: 7%
            - type: state-icon
              tap_action: toggle
              entity: light.linear_lb60z1_dimmable_led_light_bulb_level_3 # Porch bulb 2
              style:
                top: 89%
                left: 2%
            - type: state-icon
              tap_action: toggle
              entity: switch.livingroomlight_switch
              style:
                top: 95%
                left: 25%
            - type: state-icon
              # bedroom light
              tap_action: toggle
              entity: light.ge_45606_2way_dimmer_switch_level
              style:
                top: 60%
                left: 66%
            - type: state-icon
              # office light
              tap_action: toggle
              entity: light.ge_45606_2way_dimmer_switch_level_2
              style:
                top: 80%
                left: 66%
            # DOORS
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_2 # crawlspace
              style:
                top: 93%
                left: 86%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_3 # Gate
              style:
                top: 6%
                left: 96%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor_4 # kitchen
              style:
                top: 40%
                left: 19%
            - type: state-icon
              entity: binary_sensor.ecolink_doorwindow_sensor_sensor # front
              style:
                top: 89%
                left: 14%
            # MOTION
            - type: state-icon
              entity: binary_sensor.ecolink_motion_detector_sensor # back bedroom
              style:
                top: 13%
                left: 65%
            - type: state-icon
              entity: binary_sensor.kitchen_motion # kitchen
              style:
                top: 56%
                left: 18%
            - type: state-icon
              entity: binary_sensor.livingroom_motion # living room
              style:
                top: 80%
                left: 35%
            - type: state-icon
              entity: binary_sensor.office_motion # office
              style:
                top: 82%
                left: 75%
            - type: state-icon
              entity: binary_sensor.bedroom_motion # bedroom
              style:
                top: 50%
                left: 75%
            # CAMERAS
            - type: state-icon
              entity: camera.lrkitchen
              style:
                top: 68%
                left: 16%
            - type: state-icon
              entity: camera.back
              style:
                top: 8%
                left: 30%
            - type: state-icon
              entity: camera.porch
              style:
                top: 73%
                left: 5%
            - type: state-icon
              entity: camera.side
              style:
                top: 6%
                left: 88%
            - type: state-icon
              entity: camera.hall
              style:
                top: 23%
                left: 50%
            - type: state-icon
              entity: camera.office
              style:
                top: 74%
                left: 80%
            - type: state-icon
              entity: camera.bedrm
              style:
                top: 62%
                left: 80%
            # TEMPERATURES
            - type: state-label
              entity: sensor.bedroomsensor_temperature
              style:
                top: 50%
                left: 66%
            - type: state-label
              entity: sensor.pi2graphite_1wire_bedroom
              style:
                top: 42%
                left: 78%
            - type: state-label
              entity: sensor.pi2graphite_1wire_office
              style:
                top: 94%
                left: 65%
            - type: state-label
              entity: sensor.officesensor_temperature
              style:
                top: 94%
                left: 77%
            - type: state-label
              entity: sensor.kitchensensor_temperature
              style:
                top: 48%
                left: 20%
            - type: state-label
              entity: sensor.lrmotion_temperature
              style:
                top: 90%
                left: 35%
            - type: state-label
              entity: sensor.2gig_technologies_ct101_thermostat_iris_temperature
              style:
                top: 65%
                left: 40%
        - type: picture-entity
          entity: switch.side_state
          camera_image: camera.side
        - type: picture-entity
          entity: switch.hall_state
          camera_image: camera.hall
        - type: entities
          title: Z-Wave
          entities:
            - zwave.aeotec_zw090_zstick_gen5_us
            - zwave.2gig_technologies_ct101_thermostat_iris
            - zwave.bedroomsensor
            - zwave.ecolink_doorwindow_sensor
            - zwave.ecolink_doorwindow_sensor_2
            - zwave.ecolink_doorwindow_sensor_3
            - zwave.ecolink_doorwindow_sensor_4
            - zwave.ecolink_motion_detector
            - zwave.ge_45606_2way_dimmer_switch
            - zwave.ge_45606_2way_dimmer_switch_2
            - zwave.inovelli_unknown_type2400_id2400
            - zwave.kitchensensor
            - zwave.linear_lb60z1_dimmable_led_light_bulb
            - zwave.linear_lb60z1_dimmable_led_light_bulb_2
            - zwave.linear_lb60z1_dimmable_led_light_bulb_3
            - zwave.lrmotion
            - zwave.officesensor
            - zwave.zipato_bulb_2
      # CENTER COLUMN
      - type: vertical-stack
        cards:
        - type: entities
          show_header_toggle: false
          title: Controls
          entities:
            - input_select.alarmstate
            - input_boolean.cameras_silent
            - input_boolean.enable_interior_cameras
            - switch.linear_wa105dbz1_main_operated_siren_switch
            - input_boolean.no_alarm_delay
            - group.lights
            - input_boolean.enable_randomlights
            - input_boolean.enable_motion
        - type: picture-entity
          entity: switch.porch_state
          camera_image: camera.porch
        - type: picture-entity
          entity: switch.bedrm_state
          camera_image: camera.bedrm
        - type: entities
          title: Climate
          entities:
            - sensor.thermostat_fan_state
            - sensor.thermostat_operation_mode
            - climate.2gig_technologies_ct101_thermostat_iris_cooling_1
            - climate.2gig_technologies_ct101_thermostat_iris_heating_1
        - type: entities
          title: Lights
          entities:
            # kitchen
            - light.linear_lb60z1_dimmable_led_light_bulb_level
            - light.linear_lb60z1_dimmable_led_light_bulb_level_2
            # porch
            - light.linear_lb60z1_dimmable_led_light_bulb_level_3
            - light.zipato_bulb_2_level
            # Living Room
            - switch.livingroomlight_switch
            # Bedroom
            - light.ge_45606_2way_dimmer_switch_level
            # Office
            - light.ge_45606_2way_dimmer_switch_level_2
      # RIGHT COLUMN
      - type: vertical-stack
        cards:
        - type: picture-entity
          entity: switch.back_state
          camera_image: camera.back
        - type: picture-entity
          entity: switch.lrkitchen_state
          camera_image: camera.lrkitchen
        - type: picture-entity
          entity: switch.office_state
          camera_image: camera.office
        - type: weather-forecast
          entity: weather.dark_sky
        - type: entities
          show_header_toggle: false
          title: Cameras
          entities:
            - sensor.back_events
            - sensor.back_status
            - switch.back_state
            - sensor.bedrm_events
            - sensor.bedrm_status
            - switch.bedrm_state
            - sensor.lrkitchen_events
            - sensor.lrkitchen_status
            - switch.lrkitchen_state
            - sensor.office_events
            - sensor.office_status
            - switch.office_state
            - sensor.porch_events
            - sensor.porch_status
            - switch.porch_state
            - sensor.side_events
            - sensor.side_status
            - switch.side_state
            - sensor.hall_events
            - sensor.hall_status
            - switch.hall_state
      # END RIGHT COLUMN - NO MORE COLUMNS!
